name: "Sample React CI Pipeline / Workflow"

on: 
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: "Checkout Code"
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Use LTS version for stability
          
      # Install dependencies
      - name: "Install Dependencies"
        run: npm ci # Clean and fast install

      # Build the project
      - name: "Build Project"
        run: npm run build # Run the build script as defined in package.json

      # Run tests
      - name: "Run Tests"
        run: npm test -- --watchAll=false # Execute tests without watching