name: "Sample React CI Pipeline / Workflow"

on: 
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: "Checkout Code"
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Changed to LTS version; Node.js 21 is not stable

      # Install dependencies
      - name: "Install Dependencies"
        run: npm ci # Using npm ci for cleaner, faster installs in CI environments

      # Run tests
      - name: "Run Tests"
        run: npm test
        env:
          CI: true # Ensures proper CI test behavior (e.g., in Create React App)

      # Build the project
      - name: "Build Project"
        run: npm run build